[2024-01-28T17:23:38.011+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_dag_with_taskflow_api_v0.greet manual__2024-01-28T11:53:27.206792+00:00 [queued]>
[2024-01-28T17:23:38.021+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_dag_with_taskflow_api_v0.greet manual__2024-01-28T11:53:27.206792+00:00 [queued]>
[2024-01-28T17:23:38.021+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-28T17:23:38.070+0530] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2024-01-28 11:53:27.206792+00:00
[2024-01-28T17:23:38.073+0530] {standard_task_runner.py:60} INFO - Started process 3878 to run task
[2024-01-28T17:23:38.076+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'sample_dag_with_taskflow_api_v0', 'greet', 'manual__2024-01-28T11:53:27.206792+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/3-create-dag-with-tfapi.py', '--cfg-path', '/tmp/tmpfa0pu1g4']
[2024-01-28T17:23:38.079+0530] {standard_task_runner.py:88} INFO - Job 301: Subtask greet
[2024-01-28T17:23:38.157+0530] {task_command.py:423} INFO - Running <TaskInstance: sample_dag_with_taskflow_api_v0.greet manual__2024-01-28T11:53:27.206792+00:00 [running]> on host mh1.myguest.virtualbox.org
[2024-01-28T17:23:38.315+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hdu' AIRFLOW_CTX_DAG_ID='sample_dag_with_taskflow_api_v0' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T11:53:27.206792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T11:53:27.206792+00:00'
[2024-01-28T17:23:38.316+0530] {logging_mixin.py:188} INFO - Hello world, my name is John  and iam 25 years old 
[2024-01-28T17:23:38.317+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-01-28T17:23:38.328+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sample_dag_with_taskflow_api_v0, task_id=greet, execution_date=20240128T115327, start_date=20240128T115338, end_date=20240128T115338
[2024-01-28T17:23:38.376+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T17:23:38.391+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
