[2024-01-28T18:15:59.251+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v1.task1 scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T18:15:59.267+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v1.task1 scheduled__2024-01-27T00:00:00+00:00 [queued]>
[2024-01-28T18:15:59.268+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-28T18:15:59.301+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-01-27 00:00:00+00:00
[2024-01-28T18:15:59.305+0530] {standard_task_runner.py:60} INFO - Started process 4611 to run task
[2024-01-28T18:15:59.313+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_catchup_n_backfill_v1', 'task1', 'scheduled__2024-01-27T00:00:00+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/4-create-dag-with-catchup_n_backfill.py', '--cfg-path', '/tmp/tmptkjhkrm6']
[2024-01-28T18:15:59.315+0530] {standard_task_runner.py:88} INFO - Job 323: Subtask task1
[2024-01-28T18:15:59.382+0530] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_n_backfill_v1.task1 scheduled__2024-01-27T00:00:00+00:00 [running]> on host mh1.myguest.virtualbox.org
[2024-01-28T18:15:59.510+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hdu' AIRFLOW_CTX_DAG_ID='dag_with_catchup_n_backfill_v1' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T00:00:00+00:00'
[2024-01-28T18:15:59.512+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T18:15:59.516+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo testing']
[2024-01-28T18:15:59.526+0530] {subprocess.py:86} INFO - Output:
[2024-01-28T18:15:59.527+0530] {subprocess.py:93} INFO - testing
[2024-01-28T18:15:59.528+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T18:15:59.569+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_n_backfill_v1, task_id=task1, execution_date=20240127T000000, start_date=20240128T124559, end_date=20240128T124559
[2024-01-28T18:15:59.614+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T18:15:59.637+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
